orogene/orogene

- crates/rogga/src/cache.rs
This pretty much does what it says on the tin! (I'm mostly just familiarizing myself with the codebase, here.)
> Add file mode to rogga package cache entry

- README.md
I wanted to send out a PR purely for the sake of sending out a PR ^^
> Add a very tiny readme

- .editorconfig
- Cargo.lock
- Cargo.toml
- commands/cmd-restore/Cargo.toml
- commands/cmd-restore/src/lib.rs
- commands/cmd-view/src/lib.rs
- crates/cacache/src/content/read.rs
- crates/cacache/src/content/write.rs
- crates/oro-client/Cargo.toml
- crates/oro-client/src/http_client.rs
- crates/oro-client/src/http_client/mod.rs
- crates/oro-client/src/http_client/tcp.rs
- crates/oro-client/src/http_client/tls.rs
- crates/oro-client/src/lib.rs
- crates/rogga/Cargo.toml
- crates/rogga/src/cache.rs
- crates/rogga/src/fetch/dir.rs
- crates/rogga/src/fetch/mod.rs
- crates/rogga/src/fetch/registry.rs
- crates/rogga/src/integrity.rs
- crates/rogga/src/lib.rs
- crates/rogga/src/package.rs
- src/lib.rs
Mostly merging it now because it also adds things like request pooling and stuff. Code could use a cleanup, too.
> very basic restore command

- crates/oro-node-semver/src/lib.rs
- crates/oro-node-semver/src/version_req.rs
"2.x" becomes ">=2.0.0 <3.0.0-0"
> Show pre-release component for ranges that have < upper bound

- LICENSE.md
> Point the members link to the MEMBERS.md doc

- .github/workflows/ci.yml
> fix ci stuff after tauri merge

- .github/workflows/ci.yml
- antimony/package-lock.json
- antimony/package.json
- antimony/src/App.vue
- antimony/src/components/HelloWorld.vue
- antimony/src/main.ts
- antimony/src/router/index.ts
- antimony/src/views/About.vue
- antimony/src/views/Home.vue
On windows, Vue router currently prevents the window js from loading at all. Issue [here](https://github.com/vuejs/vue-router-next/issues/304)
> #49 Added vue-router, prettier, and prettier action

- antimony/src/commands/oro-core.ts
Just as an example of what we can do to decouple functionality from the ui itself.
Not in use yet as the relevant files are being worked on
> Created composable function for ping command

- crates/oro-manifest/src/lib.rs
> Make files field in the manifest optional

- .gitignore
- .gitmodules
- Cargo.lock
- crates/obelisk/Cargo.toml
- crates/obelisk/README.md
- crates/obelisk/build.rs
- crates/obelisk/node.cpp
- crates/obelisk/node_c_api/node_ext_api.cc
- crates/obelisk/node_c_api/node_ext_api.h
- crates/obelisk/src/lib.rs
This PR creates a new crate `obelisk` that has Node as its git submodule.
Custom C API is used to call Node from Rust.
Node is checked out at version 14.14.0.
Before we make some automation, build needs some manual steps.
Because of that, CI build will fail and that's why I commented out the relevant lines.
> Attempt to embed Node in Orogene

- crates/node-maintainer/src/maintainer.rs
Suggested way to review: https://github.com/orogene/orogene/pull/119/files?w=1
> parallelize dependency fetching

- crates/node-maintainer/src/maintainer.rs
I swear it didn't work before!
> Use boxed to simplify maintainer's locking

- Cargo.lock
- Cargo.toml
- crates/oro-client/src/api/packument.rs
- src/lib.rs
Fixes: https://github.com/orogene/orogene/issues/179
> feat(log): write verbose trace to a separate debug logfile

- crates/oro-common/src/build_manifest.rs
> unshadow the actual output of BuildManifest::normalize

- crates/oro-common/src/packument.rs
> Fix deserialization for `deprecated` tag of version metadata

- .github/workflows/ci.yml
Fixes #228 
Reduce CI time by ~75%
Check 👇 for CI time
https://github.com/anurag-rajawat/orogene/actions/runs/4671020273
https://github.com/anurag-rajawat/orogene/actions/runs/4670949343
> feat(ci): Cache cargo dependencies (#228)

- Cargo.lock
- Cargo.toml
- book/src/SUMMARY.md
- book/src/commands/add.md
- book/src/commands/remove.md
- book/src/guide/node_modules.md
- crates/oro-package-spec/src/lib.rs
- crates/oro-pretty-json/src/lib.rs
- src/apply_args.rs
- src/commands/add.rs
- src/commands/apply.rs
- src/commands/mod.rs
- src/commands/reapply.rs
- src/commands/remove.rs
- src/commands/view.rs
- src/lib.rs
- src/nassun_args.rs
- tests/help.rs
- tests/snapshots/help__add.snap
- tests/snapshots/help__remove.snap
- tests/snapshots/help__view.snap
Fixes: https://github.com/orogene/orogene/issues/238
> feat(add): add `oro add` command for adding new deps

- crates/nassun/src/fetch/git.rs
This PR implements querying git dependencies by semver information.
> Query git dependencies with semver info

- Cargo.lock
- Cargo.toml
- book/src/SUMMARY.md
- book/src/guide/telemetry.md
- src/lib.rs
- tests/snapshots/help__add.snap
- tests/snapshots/help__apply.snap
- tests/snapshots/help__ping.snap
- tests/snapshots/help__reapply.snap
- tests/snapshots/help__remove.snap
- tests/snapshots/help__view.snap
Fixes: https://github.com/orogene/orogene/issues/261
> feat(telemetry): implement opt-in crash and usage telemetry

- crates/nassun/src/entries.rs
- crates/nassun/src/error.rs
- crates/nassun/src/fetch/dir.rs
- crates/nassun/src/resolver.rs
- crates/nassun/src/tarball.rs
- crates/nassun/src/wasm.rs
- crates/node-maintainer/src/error.rs
- crates/node-maintainer/src/linkers/hoisted.rs
- crates/node-maintainer/src/linkers/isolated.rs
- crates/node-maintainer/src/linkers/mod.rs
- crates/node-maintainer/src/maintainer.rs
- crates/node-maintainer/src/resolver.rs
- crates/oro-script/src/error.rs
- crates/oro-script/src/lib.rs
Fixes: https://github.com/orogene/orogene/issues/249
> feat(error): Add extra context to all std::io::Error messages

- Cargo.lock
- Cargo.toml
- crates/nassun/src/client.rs
- crates/oro-client/Cargo.toml
- crates/oro-client/src/client.rs
- src/lib.rs
- tests/snapshots/help__add.snap
- tests/snapshots/help__apply.snap
- tests/snapshots/help__ping.snap
- tests/snapshots/help__reapply.snap
- tests/snapshots/help__remove.snap
- tests/snapshots/help__view.snap
This pr implements request retry for the [issue#147](https://github.com/orogene/orogene/issues/147)
> feat: support request fetch-retries

- Dockerfile
- README.md
- src/lib.rs
- small Dockerfile to compile orogene
- short info into README.md for the Dockerfile
- remove a compile error
> add Dockerfile to compile orogene in a rust-debian-bookworm container
